[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tides"
version = "0.1.0"
description = "Utilities for Tillamook tide processing"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["click"]
